plugins:
  - rubocop-performance
  - rubocop-rake

# Set this to the minimum supported ruby in the gemspec. Otherwise
# we get errors if our ruby version doesn't match.
AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

# Allow `!` methods in this file to return boolean values.
Naming/PredicateMethod:
  Exclude:
    - 'lib/zip/bzip2/libbz2.rb'
