name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: ['3.0', '3.1', '3.2', '3.3', '3.4', head, jruby, jruby-head, truffleruby, truffleruby-head]
        include:
          - os: macos
            ruby: '3.0'
          - os: windows
            ruby: '3.0'
    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.os == 'windows' }}
    steps:
    - name: Checkout rubyzip-bzip2 code
      uses: actions/checkout@v4

    - name: Install and set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: latest
        bundler-cache: true

    - name: Install bzip2 library
      if: matrix.os == 'windows'
      run: |
        wget https://github.com/philr/bzip2-windows/releases/download/v1.0.8.0/bzip2-dll-1.0.8.0-win-x64.zip
        Expand-Archive -Path bzip2-dll-1.0.8.0-win-x64.zip -DestinationPath C:\hostedtoolcache\windows\Ruby\${{ matrix.ruby }}\x64\bin

    - name: Run the tests
      env:
        JRUBY_OPTS: --debug
      run: bundle exec rake

    - name: Coveralls
      if: matrix.os == 'ubuntu' && !endsWith(matrix.ruby, 'head')
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: ${{ matrix.ruby }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
